---
addons:
  - (( append ))
  - name: loggregator_agent
    include:
      stemcell:
        - os: ubuntu-xenial

    exclude:
      jobs:
        - { release: cf-smoke-tests, name: smoke_tests }

    jobs:
      - name: loggregator_agent
        release: loggregator-agent
        properties:
          loggregator:
            tls:
              ca_cert:    (( grab meta.certs.loggregator.agent.ca_cert ))
              agent:
                cert:     (( grab meta.certs.loggregator.agent.cert ))
                key:      (( grab meta.certs.loggregator.agent.key ))
          deployment:     (( grab name ))
          metrics:
            server_name:  loggregator_agent_metrics
            .:            (( inject meta.certs.metrics.loggregator_agent_metrics_tls ))

      - name: prom_scraper
        release:  loggregator-agent
        properties:
          scrape:
            tls:          (( grab meta.certs.metrics.prom_scraper_scrape_tls ))
          metrics:
            server_name:  prom_scraper_metrics
            .:            (( inject meta.certs.metrics.prom_scraper_metrics_tls ))
