---
features:
  use_dns_addresses: true

meta:
  dns:
    query:
      query:      '*'
      deployment: (( grab name ))
      domain:     bosh
      network:    (( grab params.cf_internal_network ))

addons:
  - (( append ))
  - name: bosh-dns-aliases
    jobs:
      - name: bosh-dns-aliases
        release: bosh-dns-aliases
        properties:
          aliases:
            - domain: '_.cell.service.cf.internal'
              targets:
                - .: (( inject meta.dns.query ))
                  query: '_'
                  instance_group: cell
                  network: (( grab params.cf_runtime_network ))

            - domain: auctioneer.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  query: 'q-s4'
                  instance_group: diego

            - domain: bbs.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  query: 'q-s4'
                  instance_group: bbs

            - domain: blobstore.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: blobstore

            - domain: cc-uploader.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: diego

            - domain: cloud-controller-ng.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: api

            - domain: credhub.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: credhub

            - domain: doppler.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: doppler

            - domain: file-server.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: api

            - domain: gorouter.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: router
                  network: (( grab params.cf_edge_network ))

            - domain: locket.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: bbs

            - domain: loggregator-trafficcontroller.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: loggregator-trafficcontroller

            - domain: policy-server.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: api

            - domain: reverse-log-proxy.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: loggregator-trafficcontroller

            - domain: routing-api.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: api

            - domain: silk-controller.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: bbs

            - domain: sql-db.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: postgres
                  network: (( grab params.cf_db_network ))

            - domain: ssh-proxy.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: router
                  network: (( grab params.cf_edge_network ))

            - domain: tps.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: diego

            - domain: uaa.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: uaa

            - domain: apiserver.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: as-api
                  network: (( grab params.autoscaler_network ))

            - domain: autoscalerscheduler.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: as-scheduler
                  network: (( grab params.autoscaler_network ))

            - domain: servicebroker.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: as-broker
                  network: (( grab params.autoscaler_network ))

            - domain: metricscollector.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: as-collector
                  network: (( grab params.autoscaler_network ))

            - domain: eventgenerator.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: as-scaler
                  network: (( grab params.autoscaler_network ))

            - domain: scalingengine.service.cf.internal
              targets:
                - .: (( inject meta.dns.query ))
                  instance_group: as-engine
                  network: (( grab params.autoscaler_network ))
