---
addons:
- (( append ))
- name: loggregator_agent
  include:
    stemcell:
    - os: ubuntu-xenial
  exclude:
    jobs:
    - name: smoke_tests
      release: cf-smoke-tests
  jobs:
  - name: loggregator_agent
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          ca_cert: (( grab meta.certs.loggregator.ca ))
          agent: (( grab meta.certs.loggregator.metron.server ))
      metron_agent:
        deployment: (( grab name ))
      metron_endpoint:
        shared_secret: (( grab meta.loggregator.endpoint_secret ))