---

meta:
  diego_bbs_client_tls:
    ca_cert:     (( grab meta.certs.cf_internal.diego_bbs_client.ca_cert ))
    client_cert: (( grab meta.certs.cf_internal.diego_bbs_client.cert ))
    client_key:  (( grab meta.certs.cf_internal.diego_bbs_client.key ))
    require_tls: true

instance_groups:
  - name: bbs
    jobs:
      - name: bbs
        release: diego
        properties:
          bpm:
            enabled: true
          diego:
            bbs:
              skip_consul_lock: true
              detect_consul_cell_registrations: false
              active_key_label: key1
              encryption_keys:
                - label: key1
                  passphrase: (( vault meta.vault "/diego/encryption_key:value" ))
              ca_cert:     (( grab meta.certs.cf_internal.diego_bbs_server.ca_cert ))
              server_cert: (( grab meta.certs.cf_internal.diego_bbs_server.cert ))
              server_key:  (( grab meta.certs.cf_internal.diego_bbs_server.key ))

              auctioneer:
                ca_cert:     (( grab meta.certs.cf_internal.diego_auctioneer_client.ca_cert ))
                client_cert: (( grab meta.certs.cf_internal.diego_auctioneer_client.cert ))
                client_key:  (( grab meta.certs.cf_internal.diego_auctioneer_client.key ))
                require_tls: true
              rep: (( grab meta.diego_rep_client_tls ))
              sql:
                #no ssl to the sql backend
                require_ssl: false
                db_driver: (( grab params.diegodb_scheme ))
                max_open_connections: 500
                db_port: (( grab params.diegodb_port ))
                db_schema: (( grab params.diegodb_name ))
                db_host: (( grab params.diegodb_host ))
                db_password: (( grab params.diegodb_password ))
                db_username: (( grab params.diegodb_user ))
          enable_consul_service_registration: false
          loggregator: (( grab meta.diego_loggregator_client_tls ))

      - name: silk-controller
        release: silk
        properties:
          ca_cert:     (( grab meta.certs.silk.controller.ca_cert ))
          server_cert: (( grab meta.certs.silk.controller.cert ))
          server_key:  (( grab meta.certs.silk.controller.key ))
          database:
            type:     (( grab params.silkdb_scheme ))
            username: (( grab params.silkdb_user ))
            password: (( grab params.silkdb_password ))
            host:     (( grab params.silkdb_host ))
            port:     (( grab params.silkdb_port ))
            name:     (( grab params.silkdb_name ))
          silk_daemon:
            ca_cert:     (( grab meta.certs.silk.daemon.ca_cert ))
            server_cert: (( grab meta.certs.silk.daemon.cert ))
            server_key:  (( grab meta.certs.silk.daemon.key ))

      - name: locket
        release: diego
        properties:
          enable_consul_service_registration: false
          tls: (( grab meta.certs.cf_internal.diego_locket_server ))
          diego:
            locket:
              sql:
                db_host: (( grab params.locketdb_host ))
                db_port:  (( grab params.locketdb_port ))
                db_schema:  (( grab params.locketdb_name ))
                db_username:  (( grab params.locketdb_user ))
                db_password:  (( grab params.locketdb_password ))
                db_driver:  (( grab params.locketdb_scheme ))
          loggregator: (( grab meta.diego_loggregator_client_tls ))
