---
instance_groups:
- name: diego
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: {from: consul_common_link}
      consul_server: nil
      consul_client: {from: consul_client_link}

  - name: auctioneer
    release: diego
    properties:
      enable_consul_service_registration: true
      diego:
        loggregator:
          use_v2_api: true
          ca_cert: (( grab meta.certs.loggregator.ca ))
          cert: (( grab meta.certs.loggregator.metron.server.cert ))
          key: (( grab meta.certs.loggregator.metron.server.key ))
        auctioneer:
          skip_consul_lock: false
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          rep:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.rep.client ))

          ca_cert: (( grab meta.certs.diego.ca ))
          .: (( inject meta.certs.diego.auctioneer.server ))

  - name: tps
    release: capi
    properties:
      capi:
        tps:
          listener_enabled: false
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          cc:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.tps.client ))
          watcher:
            locket:
              api_location: "locket.service.cf.internal:8891"
            skip_consul_lock: false

  - name: cc_uploader
    release: capi
    properties:
      capi:
        cc_uploader:
          cc:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.cc_uploader.client ))
          mutual_tls:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.cc_uploader.server ))

  - name: route_emitter
    release: diego
    properties:
      locks:
        consul:
          enabled: true
      diego:
        route_emitter:
          bbs:
            ca_cert: (( grab meta.certs.diego.ca ))
            .: (( inject meta.certs.diego.bbs.client ))
          healthcheck_address: 127.0.0.1:17012 # to avoid conflict colocating with stager
          uaa:
            ca_cert: (( grab meta.certs.uaa.ca ))
            client_secret: (( grab meta.uaa.tcp_emitter_secret ))

  - name: scheduler
    release: cf-syslog-drain
    properties:
      scalablesyslog:
        scheduler:
          api:
            url: https://cloud-controller-ng.service.cf.internal:9023
          tls:
            client:
              ca: (( grab meta.certs.loggregator.ca ))
              cert: (( grab meta.certs.loggregator.syslogger.client.cert ))
              key: (( grab meta.certs.loggregator.syslogger.client.key ))
              adapter_cn: "ss-adapter"
            api:
              ca: (( grab meta.certs.diego.ca ))
              cert: (( grab meta.certs.loggregator.syslogger.api.cert ))
              key: (( grab meta.certs.loggregator.syslogger.api.key ))
              cn: "cloud-controller-ng.service.cf.internal"

  - name: log-cache-scheduler
    release: log-cache

  - name: log-cache-expvar-forwarder
    release: log-cache
    properties:
      loggregator_agent:
        tls:
          ca_cert: (( grab meta.certs.loggregator.ca ))
          cert: (( grab meta.certs.loggregator.logcache.cert ))
          key: (( grab meta.certs.loggregator.logcache.key ))
      counters: []
      gauges: []
      maps:
      - name: worker-assignments
        source_id: log-cache-scheduler
        addr: http://localhost:6064/debug/vars
        template: "{{.WorkerAssignments | jsonMap}}"
      - name: worker-health
        source_id: log-cache-scheduler
        addr: http://localhost:6064/debug/vars
        template: "{{.WorkerHealth | jsonMap}}"