releases:
- name:    bpm
  version: "1.1.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" releases.bpm.version ))
  sha1:    82e83a5e8ebd6e07f6ca0765e94eb69e03324a19

- name:    capi
  version: "1.83.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/capi-release?v=" releases.capi.version ))
  sha1:    339e21175080d77e648e0181b394a6aa2679d271

- name:    cf-networking
  version: "2.23.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-networking-release?v=" releases.cf-networking.version ))
  sha1:    d1e8982a26287edc239116c2013de098fb9e15a8

- name:    cf-smoke-tests
  version: "40.0.112"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-smoke-tests-release?v=" releases.cf-smoke-tests.version ))
  sha1:    26a8c40836fe8b0168fd4f0b02260d9b70cec595

- name:    cflinuxfs2
  version: "1.286.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-release?v=" releases.cflinuxfs2.version ))
  sha1:    cbee634a14c42b7f9be48506f6a551960cac1652

- name:    cflinuxfs3
  version: "0.113.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cflinuxfs3-release?v=" releases.cflinuxfs3.version ))
  sha1:    5132bdcc0975d404033e9dafba9d2acea50085a4

- name:    cf-cli
  version: "1.16.0"
  url:     (( concat "https://bosh.io/d/github.com/bosh-packages/cf-cli-release?v=" releases.cf-cli.version ))
  sha1:    fa5d89b88a07822665d82e00f1629b98935b17e8
  
- name:    diego
  version: "2.34.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/diego-release?v=" releases.diego.version ))
  sha1:    2ef1517f78126e0ef079244a83941a83b6dd0731

- name:    garden-runc
  version: "1.19.3"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=" releases.garden-runc.version ))
  sha1:    76810f5dd66d8320b344b3eca197c5b669a3a633

- name:    loggregator
  version: "105.5"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=" releases.loggregator.version ))
  sha1:    62b9210def7c5179f6088b9449f551f57f1a1ee8

- name:    loggregator-agent
  version: "3.9"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/loggregator-agent-release?v=" releases.loggregator-agent.version ))
  sha1:    bf723af956a61c7b51db0ba535c871bad24dd289

- name:    log-cache
  version: "2.2.2"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=" releases.log-cache.version ))
  sha1:    634dd3e134d0dac00f3f86beb00c06653579af4b

- name:    nats
  version: "27"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/nats-release?v=" releases.nats.version ))
  sha1:    9817e8e460b8619a99a0a0fbec8220dc12b2a6f5

- name:    routing
  version: "0.188.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=" releases.routing.version ))
  sha1:    d3420851c470790e8980ff0c506f75e3e52c15d9

- name:    statsd-injector
  version: "1.10.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/statsd-injector-release?v=" releases.statsd-injector.version ))
  sha1:    255cfb2815e692576efd5caa082f5a48f6799ca0

- name:    cf-syslog-drain
  version: "10.2"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/cf-syslog-drain-release?v=" releases.cf-syslog-drain.version ))
  sha1:    fe9fd8946c39554425b534cdb8ce14f3923a31f8

- name:    uaa
  version: "72.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=" releases.uaa.version ))
  sha1:    7130e5ac640ed1e1f52c09e76995e4d0680f3b45

- name:    silk
  version: "2.23.0"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/silk-release?v=" releases.silk.version ))
  sha1:    ecd2f3f05a308ae1920d17f941e38be0a5ec5ee9

- name:    bosh-dns-aliases
  version: "0.0.3"
  url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=" releases.bosh-dns-aliases.version ))
  sha1:    b0d0a0350ed87f1ded58b2ebb469acea0e026ccc

