---
instance_groups:
- name: smoke-tests
  jobs:
  - name: smoke_tests
    release: cf-smoke-tests
    properties:
      smoke_tests:
        api: (( concat "https://api." params.system_domain ))
        apps_domain: (( grab params.apps_domains[0] ))
        client: cf_smoke_tests
        client_secret: (( grab meta.uaa.cf_smoke_tests ))
        org: cf_smoke_tests_org
        space: cf_smoke_tests_space
        cf_dial_timeout_in_seconds: 300
        skip_ssl_validation: (( grab params.skip_ssl_validation ))
