---
instance_groups:
- name: syslogger
  jobs:
  - name: adapter
    release: cf-syslog-drain
    properties:
      scalablesyslog:
        adapter:
          tls:
            ca: (( grab meta.certs.loggregator.ca ))
            cert: (( grab meta.certs.loggregator.syslogger.server.cert ))
            key: (( grab meta.certs.loggregator.syslogger.server.key ))
            cn: ss-adapter
          logs:
            addr: reverse-log-proxy.service.cf.internal:8082
        adapter_rlp:
          tls:
            ca: (( grab meta.certs.loggregator.ca ))
            cert: (( grab meta.certs.loggregator.syslogger.rlp.cert ))
            key: (( grab meta.certs.loggregator.syslogger.rlp.key ))
            cn: ss-adapter-rlp
