---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/genesis

inputs:
- name: git
  path: kit
- name: git-ci

run:
  path: git-ci/ci/tasks/test-flight/task

params:
  GENESIS_HONOR_ENV:    1
  GIT_NAME:             Stark & Wayne CI Bot
  GIT_EMAIL:            ci@starkandwayne.com
  VAULT_URI:            ((vault.url))
  VAULT_TOKEN:          ((vault.token))
  KIT_SHORTNAME:        bosh
  BOSH_ENVIRONMENT:     ((bosh.uri))
  BOSH_CA_CERT:         ((bosh.ca))
  BOSH_CLIENT:          ((bosh.username))
  BOSH_CLIENT_SECRET:   ((bosh.password))