---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-go
    tag: '1.14'

inputs:
  - name: git-ci
  - name: git
  - name: bosh-deployment

outputs:
  - name: git

run:
  path: git-ci/ci/scripts/get-latest-bosh-deployment
