---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.ops.scalecf.net/genesis-community/concourse-go
    tag:        latest

inputs:
  - name: git-ci
  - name: git
  - name: upstream

outputs:
  - name: git

run:
  path: git-ci/ci/scripts/get-latest-upstream
