---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((image/genesis.url))
    tag:        ((image/genesis.tag))

inputs:
- name: version
- name: git
- name: git-ci
- name: build

outputs:
- name: gh
- name: notifications

params:
  PRERELEASE:       1
  RELEASE_ROOT:     gh
  NOTIFICATION_OUT: notifications
  DEVELOP_BRANCH:   develop
  RELEASE_BRANCH:   main
  GITHUB_OWNER:     genesis-community
  GIT_EMAIL:        genesis-ci@rubidiumstudios.com
  GIT_NAME:         Genesis CI Bot

run:
  path: git-ci/ci/scripts/release
