meta:
  releases:
    - name:    bosh
      version: "270.12.0"
      sha1:    ecb69fdc834e962cc66747f2a9f57470a57401f9
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh?v=" meta.releases.bosh.version ))

    - name:    bpm
      version: "1.1.7"
      sha1:    e7d474c3a205fa4438ea5a60d3b59479939163aa
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=" meta.releases.bpm.version ))

    - name:    uaa
      version: "74.15.0"
      sha1:    27cf2309644d7c3b6b41c5ee32775b63707062a9
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=" meta.releases.uaa.version ))

    - name:    credhub
      version: "2.5.11"
      sha1:    f1810c1e662a1c76f40911cffd1d159204c9a661
      url:     (( concat "https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=" meta.releases.credhub.version ))

    - name:    garden-runc
      version: "1.19.10"
      sha1:    6d3a30a5d90b0ab7bd89fddf7fa22b9a4cc08b0d
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=" meta.releases.garden-runc.version ))

    - name:    port-forwarding
      version: "6"
      sha1:    40d0d26a217bf4f7398c1d01ffd47619349a2639
      url:     (( concat "https://github.com/cloudfoundry-community/port-forwarding-boshrelease/releases/download/v" meta.releases.port-forwarding.version "/port-forwarding-" meta.releases.port-forwarding.version ".tgz" ))

    - name:    os-conf
      version: "21.0.0"
      sha1:    7579a96515b265c6d828924bf4f5fae115798199
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=" meta.releases.os-conf.version ))

    - name:    vault-credhub-proxy
      version: "1.1.5"
      sha1:    4e5a203d3a4e71429036cc617af11862de7d34c5
      url:     https://s3-eu-west-1.amazonaws.com/bucc-compiled-releases/vault-credhub-proxy-1.1.5-ubuntu-xenial-621.29-20191211-095033-930927224.tgz


    - name:    bosh-aws-cpi
      version: "81"
      sha1:    a70c68afc3733a4c1f486e3e526dac9d5edaea21
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-aws-cpi-release?v=" meta.releases.bosh-aws-cpi.version ))

    - name:    bosh-azure-cpi
      version: "37.2.0"
      sha1:    f658b25b6404a5b5676ab6379b99170f300a5124
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-azure-cpi-release?v=" meta.releases.bosh-azure-cpi.version ))

    - name:    bosh-openstack-cpi
      version: "44"
      sha1:    7c9be83eb11214db85ef5320f26ec9db8fab353f
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-openstack-cpi-release?v=" meta.releases.bosh-openstack-cpi.version ))

    - name:    bosh-google-cpi
      version: "30.0.0"
      sha1:    fe4643b66f56dfd8a58df70b647bdc7d7e0c1273
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-google-cpi-release?v=" meta.releases.bosh-google-cpi.version ))

    - name:    bosh-vsphere-cpi
      version: "53.0.8"
      sha1:    3f017dbaf2e6b01a48da2f4eaf3fae44bbca8156
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-vsphere-cpi-release?v=" meta.releases.bosh-vsphere-cpi.version ))

    - name:    bosh-warden-cpi
      version: "41"
      sha1:    c260724097795d7253f7d66e834921925b6aa454
      url:     (( concat "https://bosh.io/d/github.com/cloudfoundry/bosh-warden-cpi-release?v=" meta.releases.bosh-warden-cpi.version ))


  stemcells:
    aws:
      url:  https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent?v=621.59
      sha1: d77ced450b5bd7d9dc8562c5899ec723e67002fd
    azure:
      url:  https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-xenial-go_agent?v=621.59
      sha1: 7e3db321e50ce08ce32f785932c3cba099d0d1a7
    google:
      url:  https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=621.59
      sha1: 20421205700e3adad54316a19ab88d64913b815a
    openstack:
      url:  https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-xenial-go_agent?v=621.59
      sha1: 97e194ce86c336bfcb3b5d9c8416761db05f5e27
    vsphere:
      url:  https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=621.59
      sha1: e960011ed750cfbb34948f427b02b432ffae43f2
