---
releases:
  - name:    credhub
    version: 2.0.2
    url:     https://s3.amazonaws.com/bosh-compiled-release-tarballs/credhub-2.0.2-ubuntu-xenial-170.9-20181126-235205-877343813-20181126235215.tgz
    sha1:    c1759ba08a927cd8b4476baefe5f803cbb95d515

instance_groups:
  - name: bosh
    jobs:
      - name: credhub
        release: credhub
        properties:
          credhub:
            authorization:
              acls:
                enabled: false

            authentication:
              uaa:
                ca_certs:
                  - (( vault meta.vault "/ssl/ca:certificate" ))
                url: (( concat "https://" params.static_ip ":8443" ))
                verification_key: (( vault meta.vault "/uaa/jwt:public" ))

            data_storage:
              type:     postgres
              host:     127.0.0.1
              port:     5432
              username: (( grab instance_groups.bosh.properties.postgres.user ))
              password: (( grab instance_groups.bosh.properties.postgres.password ))
              database: credhub
              require_tls: false

            encryption:
              providers:
                - name: internal
                  type: internal
              keys:
                - provider_name: internal
                  active: true
                  key_properties:
                    encryption_password: (( vault meta.vault "/credhub/encryption:key" ))

            tls:
              certificate: (( vault meta.vault "/credhub/server:certificate" ))
              private_key: (( vault meta.vault "/credhub/server:key" ))

      - name: uaa
        properties:
          uaa:
            jwt:
              revocable: true

            clients:
              director_to_credhub:
                override: true
                authorized-grant-types: client_credentials
                scope: ""
                authorities: credhub.read,credhub.write
                access-token-validity: 3600
                secret: (( vault meta.vault "/uaa/clients/director_to_credhub:secret" ))

              credhub_cli:
                override: true
                authorized-grant-types: password,refresh_token
                scope: credhub.read,credhub.write
                authorities: ""
                access-token-validity: 60
                refresh-token-validity: 1800
                secret: ""

            scim:
              users:
              - name: credhub-cli
                password: (( vault meta.vault "/uaa/users/credhub-cli:password" ))
                groups:
                  - credhub.read
                  - credhub.write

    properties:
      director:
        config_server:
          enabled: true
          url: (( concat "https://" params.static_ip ":8844/api/" ))
          ca_cert: (( vault meta.vault "/credhub/ca:certificate" ))
          uaa:
            url: (( concat "https://" params.static_ip ":8443" ))
            ca_cert: (( vault meta.vault "/ssl/ca:certificate" ))
            client_id:     director_to_credhub
            client_secret: (( vault meta.vault "/uaa/clients/director_to_credhub:secret" ))
      postgres:
        additional_databases:
          - (( append ))
          - credhub
