---
meta:
  stemcell: (( grab meta.latest_stemcells.bosh-aws-xen-hvm-ubuntu-trusty-go_agent ))

params:
  aws_subnet_id: (( param "Enter the AWS subnet ID for the proto-BOSH's subnet" ))
  aws_security_groups: (( param "Enter the list of security groups to be applied to your proto-BOSH" ))

  aws_instance_type: m3.xlarge
  aws_disk_type: gp2

vm_types:
- name: (( grab params.bosh_vm_type ))
  cloud_properties:
    instance_type: (( grab params.aws_instance_type ))
    ephemeral_disk:
      type: (( grab params.aws_disk_type ))
      size: (( grab params.ephemeral_disk_size ))
    availability_zone: (( grab params.availability_zones[0] ))

networks:
- name: (( grab params.bosh_network ))
  subnets:
  - (( inline ))
  - cloud_properties:
    security_groups: (( grab params.aws_security_groups ))
    subnet: (( grab params.aws_subnet_id ))

disk_pools:
- name: (( grab params.bosh_disk_pool ))
  cloud_properties:
    type: (( grab params.aws_disk_type ))


cloud_provider:
  template:
    name: aws_cpi
    release: bosh-aws-cpi
  ssh_tunnel:
    port: 22
    user: vcap
    host: (( grab params.static_ip ))
    private_key: (( vault meta.vault "/aws/ssh:private" ))

  properties:
    aws: (( grab instance_groups.bosh.properties.aws ))
