---
meta:
  stemcell: (( grab meta.stemcells.azure ))

params:
  azure_virtual_network: (( param "What is the Azure virtual network your BOSH vm will be placed in?" ))
  azure_subnet_name:     (( param "What is the name of the Azure subnet that your BOSH vm will be placed in?" ))

  # 2 cpu, 7G ram
  azure_instance_type:        Standard_D2_v2
  azure_persistent_disk_type: Standard_LRS
  azure_availability_set:     proto-bosh

resource_pools:
  - name: (( grab params.bosh_vm_type ))
    cloud_properties:
      instance_type: (( grab params.azure_instance_type ))
      root_disk:
        size: (( calc "params.ephemeral_disk_size + 20 * 1024" ))
      ephemeral_disk:
        use_root_disk: true
      availability_set: (( grab params.azure_availability_set ))

networks:
  - name: (( grab params.bosh_network ))
    type: manual
    subnets:
      - (( inline ))
      - cloud_properties:
          virtual_network_name: (( grab params.azure_virtual_network))
          subnet_name: (( grab params.azure_subnet_name ))

disk_pools:
  - name: (( grab params.bosh_disk_pool ))
    cloud_properties:
      storage_account_type: (( grab params.azure_persistent_disk_type ))

cloud_provider:
  template:
    name: azure_cpi
    release: bosh-azure-cpi

  ssh_tunnel:
    port: 22
    user: vcap
    host: (( grab params.static_ip ))
    private_key: (( grab params.azure.ssh_private_key ))
    private_key: (( vault meta.vault "/azure/ssh:private" ))

  properties:
    azure: 
      .: (( inject instance_groups.bosh.jobs.azure_cpi.properties.azure ))
