---
meta:
  stemcell: (( grab meta.stemcells.openstack ))

params:
  openstack_network_id: (( param "What is the UUID of the OpenStack Network BOSH will be placed in?"
  openstack_flavor: (( param "What OpenStack flavor should the BOSH VM use?" ))
  openstack_az: (( param "What AZ will the BOSH VM be placed in?" ))

resource_pools:
  - name: (( grab params.bosh_vm_type ))
    cloud_properties:
      instance_type: (( grab params.openstack_flavor ))
      availability_zone: (( grab params.openstack_az ))

networks:
  - name: (( grab params.bosh_network ))
    type: manual
    subnets:
      - (( inline ))
      - cloud_properties:
          net_id: (( grab params.openstack_network_id ))

disk_pools:
  - name: (( grab params.bosh_disk_pool ))

cloud_provider:
  template:
    name: openstack_cpi
    release: bosh-openstack-cpi

  ssh_tunnel:
    port: 22
    user: vcap
    host: (( grab params.static_ip ))
    private_key: (( vault meta.vault "/openstack/ssh:private" ))

  properties:
    openstack: 
      .: (( inject instance_groups.bosh.jobs.openstack_cpi.properties.openstack ))
