---
meta:
  stemcell: (( grab meta.stemcells.vsphere ))

params:
  # 2 core, 8G ram
  vsphere_cpu: 2
  vsphere_ram: 8192
  vsphere_disk: 40960

  vsphere_network:   (( param "Enter the vSphere network name" ))
  vsphere_disk_type: preallocated

resource_pools:
- name: (( grab params.bosh_vm_type ))
  cloud_properties:
    cpu: (( grab params.vsphere_cpu ))
    ram: (( grab params.vsphere_ram ))
    disk: (( grab params.vsphere_disk ))

networks:
- name: (( grab params.bosh_network ))
  subnets:
  - (( inline ))
  - cloud_properties:
      name: (( grab params.vsphere_network ))

disk_pools:
- name: (( grab params.bosh_disk_pool ))
  cloud_properties:
    type: (( grab params.vsphere_disk_type ))

cloud_provider:
  template:
    name: vsphere_cpi
    release: bosh-vsphere-cpi

  properties:
    vcenter: (( grab instance_groups.bosh.jobs.vsphere_cpi.properties.vcenter ))
