---
params:
  aws_key_name:    (( concat "vcap@" params.env ))
  aws_region:      (( param "What AWS region are you going to use?" ))
  aws_default_sgs: (( param "What security groups should VMs be placed in, if none are specified via Cloud Config?" ))

meta:
  default:
    azs:
      - (( replace ))
      - (( concat params.aws_region "a" ))

instance_groups:
- name: bosh
  jobs:
  - name: aws_cpi
    release: bosh-aws-cpi
  properties:
    aws:
      access_key_id:           (( vault meta.vault "/aws:access_key" ))
      secret_access_key:       (( vault meta.vault "/aws:secret_key" ))
      default_key_name:        (( grab params.aws_key_name ))
      default_security_groups: (( grab params.aws_default_sgs ))
      region:                  (( grab params.aws_region ))
    director:
      cpi_job: aws_cpi

releases:
- name:    bosh-aws-cpi
  version: 73
  sha1:    9d02123488919a325f1ed4f349090c4de6142373
  url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=73
