---
params:
  aws_key_name:    (( concat "vcap@" genesis.env ))
  aws_region:      (( param "What AWS region are you going to use?" ))
  aws_default_sgs: (( param "What security groups should VMs be placed in, if none are specified via Cloud Config?" ))
  aws_ebs_encryption: false
  aws_availability_zone: (( concat params.aws_region "a" ))

  ntp: # use AWS ntp
  - (( replace ))
  - 169.254.169.123

meta:
  default:
    azs:
      - (( replace ))
      - (( grab params.aws_availability_zone ))

instance_groups:
- name: bosh
  jobs:
  - name: aws_cpi
    release: bosh-aws-cpi
  properties:
    aws:
      access_key_id:           (( vault meta.vault "/aws:access_key" ))
      secret_access_key:       (( vault meta.vault "/aws:secret_key" ))
      default_key_name:        (( grab params.aws_key_name ))
      default_security_groups: (( grab params.aws_default_sgs ))
      region:                  (( grab params.aws_region ))
      encrypted:               (( grab params.aws_ebs_encryption ))
    director:
      cpi_job: aws_cpi

releases:
- name: bosh-aws-cpi
  .:    (( inject meta.releases.bosh-aws-cpi ))
