---
params:
  vsphere_ephemeral_datastores: (( param "Enter your vSphere ephemeral datastore pattern" ))
  vsphere_persistent_datastores: (( param "Enter your vSphere persistent datastore pattern" ))
  vsphere_clusters: (( param "Enter your vSphere clusters" ))
  vsphere_datacenter: (( param "Enter your vSphere Datacenter Name" ))

meta:
  vm_folder: (( concat params.env "/vms" ))
  template_folder: (( concat params.env "/templates" ))
  disk_path: (( concat params.env "/disks" ))

  joined_vsphere_ephemeral_datastores: (( join "|" params.vsphere_ephemeral_datastores ))
  vsphere_ephemeral_datastores: (( concat "^(" meta.joined_vsphere_ephemeral_datastores ")$" ))
  joined_vsphere_persistent_datastores: (( join "|" params.vsphere_persistent_datastores ))
  vsphere_persistent_datastores: (( concat "^(" meta.joined_vsphere_persistent_datastores ")$" ))

instance_groups:
- name: bosh
  jobs:
  - name: vsphere_cpi
    release: bosh-vsphere-cpi
  properties:
    vcenter:
      user:           (( vault meta.vault "/vsphere:user" ))
      password:       (( vault meta.vault "/vsphere:password" ))
      address:           (( vault meta.vault "/vsphere:address" ))
      datacenters:
      - name: (( grab params.vsphere_datacenter ))
        vm_folder: (( grab meta.vm_folder ))
        template_folder: (( grab meta.template_folder ))
        disk_path: (( grab meta.disk_path ))
        datastore_pattern: (( grab meta.vsphere_ephemeral_datastores ))
        persistent_datastore_pattern: (( grab meta.vsphere_persistent_datastores ))
        clusters: (( grab params.vsphere_clusters ))

    director:
      cpi_job: vsphere_cpi

releases:
- name: bosh-vsphere-cpi
  version: "52.1.1"
  sha1: b3587311b7f7403818e25989d9ed5eed99d65193
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-vsphere-cpi-release?v=52.1.1

variables: []
