---
- type: remove
  path: /instance_groups/name=bosh/properties/aws/access_key_id

- type: remove
  path: /instance_groups/name=bosh/properties/aws/secret_access_key

- type: replace
  path: /instance_groups/name=bosh/properties/aws/credentials_source?
  value: env_or_profile